services:
  - type: web
    name: anonchat
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: ADMIN_KEY
        sync: false # set in Render dashboard (Environment tab)
